[package]
name = "nexty-layout"
description = "Nexty 自研盒级布局"
version = "0.1.1"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
nexty-dom = { path = "../nexty-dom", version = "0.1.0" }
nexty-css = { path = "../nexty-css", version = "0.1.0" }
nexty-text = { path = "../nexty-text", version = "0.1.0" }

[dev-dependencies]
nexty-html = { path = "../nexty-html", version = "0.1.0" }
